config/routes.rb
Rails.application.routes.draw do
  get 'staticpages/home'

  get 'staticpages/about'

  get 'staticpages/products'

  get 'staticpages/contact'

  root 'staticpages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def home
  end

  def about
  end

  def products
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Harbortxtl</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
 
</head>
<body>
<div class="headerphoto">
<div class="headertext"></div>
<!--<div class="logo">
		
</div> -->
<div class="navbar">
	<ul>
		<li>
			<%= link_to 'HOME', staticpages_home_path, class: 'navlink' %>
		</li>
		<li>
			<%= link_to 'ABOUT', staticpages_about_path, class: 'navlink' %>
		</li>
		<li>
			<%= link_to 'PRODUCTS', staticpages_products_path, class: 'navlink' %>  
		</li>	
		<li>
			<%= link_to 'CONTACT', staticpages_contact_path, class: 'navlink' %>
		</li>
	</ul>	
</div>

<div class="sidebar">
<img src="https://photos-1.dropbox.com/s/itze8fsxlklx6ym/logo.png?dl=0?" alt="" id="logo">
	<ul>
		<li>Phone: (978) 946-9473</li>
		<li>Fax: (978) 683-9473</li>
		<li>Email: gary@harbortextiles.com</li>
	<br>
	<br>
		<li>Harbor Textiles</li>
		<li>15 Union Street</li>
		<li>Lawrence, MA 01840</li>
	<br>
	<br>
		<li>Hours of Operation:</li> 
		<li>Monday through Friday</li>
		<li>8:00 a.m. -5:00 p.m. EST</li>
</div>


<%= yield %>

	
		
</body>
</html>

app/views/staticpages/about.html.erb
<!DOCTYPE html>
<html>
<head>
<style>

</style>
</head>
<body>
	<div>
	<div class="bodycontent">
<img src="https://photos-1.dropbox.com/s/mqtefy1ocf3vi05/GaryEdelstein.jpg?dl=0" alt="" id="logo">
<br>
<br>
<br>		
		<p><span style="font-weight: 700; font-style: italic"> Gary Edelstein founded Harbor Textiles in _____ and has built the company into a one-stop-shop for all cleaning and janitorial needs. </p></span>
<br>
<br>
<br>
		<p>Supplying products for both commercial and residential application, our competitively-priced inventory includes:
		<ul>
			<li>Wiping products</li>
			<li>Gloves</li>
			<li>Bathroom supplies</li>
			<li>Trash can liners</li>
			<li>Disposable clothing</li>
			<li>Other janitorial supplies</li> 
		</ul>
		</p>

		<p>When you choose Harbor Textiles, you are not only getting a supplier, you are getting a partner. We are committed to leveraging our 30 years of expertise to ensure you get exactly what you need at a great price. 

		<p><span style="font-weight: 700">Service Areas:</span> Proudly serving the USA with a focus on the New England Region.</p>

		<div style="text-align: center;"><p><span style="font-weight: 700">Contact us today to learn more about which product(s)<br> would be best for your application!</span></p>
		</div>
	</div>
</body>
</html>

app/views/staticpages/contact.html.erb
<h1>Staticpages#contact</h1>
<p>Find me in app/views/staticpages/contact.html.erb</p>

app/views/staticpages/home.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
	<div class="bodycontent">
		<p><span style="font-weight: 700; font-size: 25px">Harbor Textiles provides quality wiping cloths, gloves, bathroom paper, trash can liners, and other cleaning supplies.</span> </p> 
		<p>Get professional-grade products at very affordable prices!</p>
	<hr>
		<p>For over 30 years, <span style="font-weight: 700">Harbor Textiles </span> has been committed to helping its customers find the right products to address a variety of janitorial and cleaning supply needs.

		<p>Our competitively-priced inventory includes:
		<ul>
			<li>Wiping products</li>
			<li>Gloves</li>
			<li>Bathroom paper</li>
			<li>Trash can liners</li>
			<li>Disposable clothing</li>
			<li>Other janitorial supplies</li> 
		</ul>
		</p>

		<p><span style="font-weight: 700">Service Areas:</span> Proudly serving the USA with a focus on the New England Region.</p>

		<div style="text-align: center;"><p><span style="font-weight: 700">Contact us today to learn more about which product(s)<br> would be best for your application!</span></p>
		</div>
	</div>
</body>
</html>

app/views/staticpages/products.html.erb
<div class="bodycontent">
<table >
  <tr>
    <th colspan="4"></th>
   </tr>
   <tr>
   <td><img src="https://photos-1.dropbox.com/s/cji80wnz63ov2sq/kim%20wipes.JPG?dl=0"><br>Kimtech Wipes</td>
    <td><img src="https://photos-1.dropbox.com/s/m2uxk2wxcb13r28/latex.JPG?dl=0">
    <br> Latex Gloves</td> 
    <td><img src="https://photos-1.dropbox.com/s/qrbmquxdy1xx52w/shop%20towels.JPG?dl=0"><br>Shop Towels</td>
    <td><img src="https://photos-1.dropbox.com/s/7mffvqjg8amycal/nitrile.JPG?dl=0"><br>Nitrile Gloves</td> 
  </tr>
</table>
<h1>Products</h1>

<p><span style="font-weight: 700">Harbor Textiles</span> offers a range of quality products to suit our customer's cleaning and janitorial needs. Browse our product selection below, or call us to discuss which products would be right for your company.</p> 

<p> Contact us for more information or a quote today!</p>
<p><span style="font-weight: 700">Product Types:</span></p>
<ul>
	<li> <A HREF="#standard">Standard Wiping Products</A></li>
	<li> <A HREF="#specialized">Specialized Wiping Products</A> </li>
	<li> <A HREF="#miscellaneous">Other Janitorial/Cleaning Products</A> </li>
</ul>
<p>To view our FULL PRODUCT BROCHURE, click here.</p>
<hr>
<A NAME="standard">
<p><span style="font-weight: 700">Standard Wiping Products:</span></p>
<div style="float: left; width: 50%;">
<ul>
	<li> Institutional rags</li>      
	<li> Nylon reinforced 4 ply paper</li>
	<li> Hydro-Knit </li>     
	<li> Spun-Lace </li>      
	<li> Recycled clothing</li>   
</ul>
</div>
<div style="float: right; width: 50%;">
<ul>	
	<li> Heavy Weight</li>
	<li> Medium Weight </li>     
	<li> Light Weight</li>    
	<li> Colored </li>    
	<li> White</li>
</ul>
</div>
<hr>
<A NAME="specialized">
<p><span style="font-weight: 700">Specialized Wiping Products: </span> Harbor Textiles offers the following unique products not always offered by other suppliers:</p>
<div style="float: left; width: 50%;">
<ul>
	<li>Authentic Cotton Diapers</li>     
	<li>Cotton Table Cloth </li>    
	<li>White and Blue Huck Towels</li> 
	<li>White and Colored Cotton Flannel</li>  
</ul>
</div>
<div style="float: right; width: 50%;">
<ul>
	<li>Elephant Paper Large Single Roll 2 ply</li>   
	<li>Elephant Paper Smaller Rolls</li>      
	<li>Pop Up Dispenser Boxes</li>
</ul>
</div>
<hr>
<A NAME="miscellaneous">
<p><span style="font-weight: 700">Other Janitorial/Cleaning Products: </span> Let us be your one-stop-shop! We strive to offer a broad selection of products so our customers can always find what they need:</p>
<div style="float: left; width: 50%;">
<ul>
	<li> Gloves </li>
	<li> Trashcan Liners </li>
	<li> Disposable Clothing </li>
</ul>>
</div>
<div style="float: right; width: 50%;">
<ul>
	<li> Rain Gear </li>
	<li> Floor Maintenance Products </li>
	<li> Bathroom Paper </li>
</ul>
</div>

<br>
<br>
<br>
<br>